Med tracking updates
Sage-Bionetworks/SageResearch pull request #37
Opened 2018-06-27 23:14 UTC by dephillipsmichael

Another set of updates from my experience developing the medication feature

2018-06-27 23:15 UTC, dephillipsmichael commented on ResearchUI/ResearchUI/iOS/RSDStepViewController.swift
> +                    navigationView.imageView?.image = UIImage(named: imageTheme.imageIdentifier)
Images from image themes were only being loaded if they were animated or fetched from the web

2018-06-27 23:18 UTC, Erin-Mounts commented on Research/Research/en.lproj/Research.strings
> +"MEDICATION_REMOVE_TITLE_%@" = "Are you sure you want to remove %@ from your current medication list?";
toremove --> to remove

2018-06-27 23:39 UTC, dephillipsmichael commented on Research/Research/en.lproj/Research.strings
> +"MEDICATION_REMOVE_TITLE_%@" = "Are you sure you want to remove %@ from your current medication list?";
good catch

2018-06-28 05:24 UTC, syoung-smallwisdom requested changes
Please move the Medication stuff from the `Research.strings` to `BridgeApp.strings`. Thanks.

Also, ping me about the imageTheme. What object are you using that doesn't implement one of the two supported image theme protocols?

2018-06-28 05:24 UTC, syoung-smallwisdom commented on Research/Research/en.lproj/Research.strings
> +"MEDICATION_REMOVE_BUTTON_TEXT" = "Yes, remove medication";
Oops, these are in this repo b/c originally I was trying to add data tracking to the Research repo rather than BridgeApp (ended up moving to BridgeApp b/c of the clientData dependency). I must have forgot to move these when I moved the rest of the code.

2018-06-28 05:24 UTC, syoung-smallwisdom commented on ResearchUI/ResearchUI/iOS/RSDStepViewController.swift
> +                    navigationView.imageView?.image = UIImage(named: imageTheme.imageIdentifier)
What object are you instantiating that doesn't implement one of these two protocols? 

This is a brittle fix, but I am not entirely certain how you got to this point.

2018-06-28 18:51 UTC, syoung-smallwisdom commented
<img width="329" alt="screen shot 2018-06-28 at 11 49 42 am" src="https://user-images.githubusercontent.com/5649217/42054518-769b475a-7ac9-11e8-8a5a-c4a0164f8522.png">

Before any details are filled in, the "Next" button should be enabled to "go to" whichever medication is first in the list.

2018-06-28 18:57 UTC, syoung-smallwisdom commented
<img width="325" alt="screen shot 2018-06-28 at 11 52 54 am" src="https://user-images.githubusercontent.com/5649217/42054659-d62dffc8-7ac9-11e8-8b18-5b2c6cf1dc32.png">

The details view should **NOT** be displayed modally. It's the next step in the series and should be displayed as "push on" with a back button, rather than an "X" button. The "Done" button should say "Next" and tapping it should push on the next detail step in the list.  Additionally, you aren't setting the backgrounds to use the appropriate `UIColor.appBackgroundDark` which is why they show up as blue instead of purple when run in mPower app.

2018-06-28 20:46 UTC, dephillipsmichael commented on Research/Research/en.lproj/Research.strings
> +"MEDICATION_REMOVE_BUTTON_TEXT" = "Yes, remove medication";
Oh ok that makes sense

2018-06-29 02:15 UTC, dephillipsmichael commented
Closing for now until I refactor

2018-06-29 02:15 UTC, closed without merging